"""empty message

Revision ID: 1bdceff315bf
Revises: 75ab574a8ba9
Create Date: 2020-09-03 00:30:30.856193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bdceff315bf'
down_revision = '75ab574a8ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('board_name', sa.String(length=100), nullable=False))
    op.drop_column('board', 'subject')
    op.drop_column('board', 'content')
    op.drop_column('board', 'create_date')
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'board', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'post_id')
    op.add_column('board', sa.Column('create_date', mysql.DATETIME(), nullable=False))
    op.add_column('board', sa.Column('content', mysql.TEXT(), nullable=False))
    op.add_column('board', sa.Column('subject', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('board', 'board_name')
    # ### end Alembic commands ###
