"""empty message

Revision ID: 329f4ba99447
Revises: 86bddf2b58e8
Create Date: 2020-09-09 15:14:56.016783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329f4ba99447'
down_revision = '86bddf2b58e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like_num')
    # ### end Alembic commands ###
