"""empty message

Revision ID: 41e7a2fb8f47
Revises: 1bdceff315bf
Create Date: 2020-09-03 01:07:56.579973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e7a2fb8f47'
down_revision = '1bdceff315bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'description')
    # ### end Alembic commands ###
