"""empty message

Revision ID: 75ab574a8ba9
Revises: 3a93627e8831
Create Date: 2020-08-31 01:07:09.485799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75ab574a8ba9'
down_revision = '3a93627e8831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'board_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'board_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
