"""empty message

Revision ID: 86bddf2b58e8
Revises: d8ac9735076a
Create Date: 2020-09-09 15:05:16.164234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bddf2b58e8'
down_revision = 'd8ac9735076a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_num')
    # ### end Alembic commands ###
