"""empty message

Revision ID: b04ae4cb2287
Revises: 7e637827d576
Create Date: 2020-09-08 13:32:16.067046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b04ae4cb2287'
down_revision = '7e637827d576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('board_num', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('category_name', sa.String(length=100), nullable=False))
    op.drop_column('category', 'board_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('board_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('category', 'category_name')
    op.drop_column('category', 'board_num')
    # ### end Alembic commands ###
