"""empty message

Revision ID: b37cb7151dcb
Revises: 329f4ba99447
Create Date: 2020-09-10 14:53:50.809477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b37cb7151dcb'
down_revision = '329f4ba99447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticeboard')
    op.add_column('board', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('post_num', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('comment', sa.Column('like_num', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('comment_num', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('like_num', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'userid')
    op.drop_column('post', 'like_num')
    op.drop_column('post', 'comment_num')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'userid')
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'like_num')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'post_num')
    op.drop_column('board', 'category_id')
    op.create_table('noticeboard',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.Column('content2', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
