"""empty message

Revision ID: b4aa0cfc8f00
Revises: b37cb7151dcb
Create Date: 2020-09-12 22:19:51.343313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4aa0cfc8f00'
down_revision = 'b37cb7151dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_num', sa.Integer(), nullable=True))
    op.add_column('post_img', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_img', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_img', type_='foreignkey')
    op.drop_column('post_img', 'post_id')
    op.drop_column('post', 'img_num')
    # ### end Alembic commands ###
