"""empty message

Revision ID: b54734b173b4
Revises: ef52a0ca66df
Create Date: 2020-08-29 14:27:57.675529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54734b173b4'
down_revision = 'ef52a0ca66df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'noticeboard', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'board_id')
    # ### end Alembic commands ###
