"""empty message

Revision ID: c360ff1f05b3
Revises: b4aa0cfc8f00
Create Date: 2020-09-12 23:33:34.328679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c360ff1f05b3'
down_revision = 'b4aa0cfc8f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruser')
    op.add_column('board', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('board', sa.Column('post_num', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'board', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('category', sa.Column('board_num', sa.Integer(), nullable=True))
    op.add_column('category', sa.Column('category_name', sa.String(length=100), nullable=False))
    op.drop_column('category', 'description')
    op.drop_column('category', 'board_name')
    op.add_column('comment', sa.Column('like_num', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('comment_num', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('img_num', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('like_num', sa.Integer(), nullable=True))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('auto_login', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_login')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'ruser', ['userid'], ['id'], ondelete='CASCADE')
    op.drop_column('post', 'like_num')
    op.drop_column('post', 'img_num')
    op.drop_column('post', 'comment_num')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'ruser', ['userid'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'like_num')
    op.add_column('category', sa.Column('board_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('category', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('category', 'category_name')
    op.drop_column('category', 'board_num')
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'post_num')
    op.drop_column('board', 'category_id')
    op.create_table('ruser',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('birth', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
