"""empty message

Revision ID: eb85bea3aa47
Revises: f4c3ffe4e963
Create Date: 2020-09-07 20:47:17.302267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb85bea3aa47'
down_revision = 'f4c3ffe4e963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruser')
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('comment_like', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('comment_like_ibfk_1', 'comment_like', type_='foreignkey')
    op.create_foreign_key(None, 'comment_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment_like', 'ruser_id')
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('post_like', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('post_like_ibfk_1', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_like', 'ruser_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_like', sa.Column('ruser_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_ibfk_1', 'post_like', 'ruser', ['ruser_id'], ['id'], ondelete='CASCADE')
    op.drop_column('post_like', 'user_id')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_2', 'post', 'ruser', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('comment_like', sa.Column('ruser_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment_like', type_='foreignkey')
    op.create_foreign_key('comment_like_ibfk_1', 'comment_like', 'ruser', ['ruser_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment_like', 'user_id')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'ruser', ['userid'], ['id'], ondelete='CASCADE')
    op.create_table('ruser',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('birth', mysql.DATETIME(), nullable=True),
    sa.Column('userid', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
