"""empty message

Revision ID: ef52a0ca66df
Revises: fbadb8c30f14
Create Date: 2020-08-29 12:39:52.743326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef52a0ca66df'
down_revision = 'fbadb8c30f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticeboard', 'content2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticeboard', sa.Column('content2', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
