"""empty message

Revision ID: f4c3ffe4e963
Revises: 6f8c69cb623b
Create Date: 2020-09-06 00:01:32.694217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4c3ffe4e963'
down_revision = '6f8c69cb623b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_ibfk_1', 'board', type_='foreignkey')
    op.drop_column('board', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('userid', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('board_ibfk_1', 'board', 'ruser', ['userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
